# Global configuration for training/testing

device: "cuda"  # "cpu" or "cuda"

# Environment
env:
  name: "SuperMarioBros-v0"
  frame_stack: 4
  gray_scale: true
  resize_shape: [64, 60]
  frame_skip: 4
  num_actions: 11

# Training
training:
  epochs: 500
  bc_epochs: 100
  updates_per_epoch: 100
  lr: 0.0005
  batch_size: 64
  gamma: 0.99
  epsilon_start: 1.0
  epsilon_end: 0.25
  epsilon_decay: 0.999
  lambda_bc: 0.99
  lambda_bc_decay: 0.95
  exploration_episodes_per_epoch: 15
  max_steps_per_episode: 300
  dqn_steps_per_epoch: 1
  replaybuffersize: 40000
  target_update: 5
  pbt_population_size: 2
  pbt_exploit_interval: 5
  save_path: "models/combined_model.pt"




data:
  expert_data_path: "data/"

# Test
test:
  env_name: SuperMarioBros-v0
  render: true
  max_steps: 5000
  num_attempts: 1

# Logging
log:
  log_dir: "runs"
  save_interval: 50000