# Global configuration for training/testing

device: "cuda"  # "cpu" or "cuda"

# Environment
env:
  name: "SuperMarioBros-v0"
  frame_stack: 4
  gray_scale: true
  resize_shape: [128, 120]
  frame_skip: 4
  num_actions: 36

# Training
training:
  epochs: 30
  updates_per_epoch: 100
  lr: 0.0005
  batch_size: 32
  gamma: 0.99
  epsilon_start: 1.0
  epsilon_end: 0.1
  epsilon_decay: 0.95
  lambda_bc: 0.99
  lambda_bc_decay: 0.96
  dqn_steps_per_epoch: 400
  replaybuffersize: 50000
  target_update: 5
  pbt_population_size: 3
  pbt_exploit_interval: 3
  save_path: "models/combined_model.pt"




data:
  expert_data_path: "data/"

# Test
test:
  env_name: SuperMarioBros-v0
  render: true
  max_steps: 5000
  num_attempts: 1

# Logging
log:
  log_dir: "runs"
  save_interval: 50000